name: Say hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola gente de pruebas y calidad del software!"
      - name: Dime la fecha
        run: date
      - name: Ficheros de la maquina
      - run: ls -l
